version: '3'

services:
  cgnas:
    build:
      context: .
      args:
        VSFTPD_PASV_MIN_PORT: ${VSFTPD_PASV_MIN_PORT}
        VSFTPD_PASV_MAX_PORT: ${VSFTPD_PASV_MAX_PORT}
    restart: always
    hostname: nas-docker
    volumes:
      - ./scripts_dynamic:/root/scripts_dynamic:ro
      - /mnt/nas/home:/nas
      - /mnt/nas/persistent:/mnt/persistent
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
