version: '3'

services:
  cgnas:
    build:
      context: .
      args:
        VSFTPD_PASV_MIN_PORT: ${VSFTPD_PASV_MIN_PORT}
        VSFTPD_PASV_MAX_PORT: ${VSFTPD_PASV_MAX_PORT}
    restart: always
    hostname: cgservice-docker
    volumes:
      - ./scripts_dynamic:/root/scripts_dynamic:ro
      - /srv/raid/home:/nas/raid
      - /srv/raid/persistent:/mnt/persistent
    ports:
      - "22:22"
