version: '3'

services:
  cgnas1804:
    build:
      context: .
      dockerfile: Dockerfile.1804
    restart: always
    hostname: nas-docker-1804
    volumes:
      - ./scripts_dynamic:/root/scripts_dynamic:ro
      - /media/raid/home:/nas/raid
      - /media/disk-0/home:/nas/disk-0
      - /media/disk-1/home:/nas/disk-1
    network_mode: host

  cgnas2004:
    build:
      context: .
      dockerfile: Dockerfile.2004
    restart: always
    hostname: nas-docker
    volumes:
      - ./scripts_dynamic:/root/scripts_dynamic:ro
      - /media/raid/home:/nas/raid
      - /media/disk-0/home:/nas/disk-0
      - /media/disk-1/home:/nas/disk-1
      - /media/raid/persistent:/mnt/persistent
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
